version: '3'

services:

  website:
    build: .
    working_dir: "/var/www"
    volumes:
      - "./:/var/www"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    env_file:
      - ".env"

  database:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=example
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
    restart: always
    volumes:
      - 'my-data:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    environment:
      PMA_ARBITRARY: 1
    restart: always
    labels:
      - "traefik.http.routers.db.rule=Host(`phpmyadmin.${PROJECT_BASE_URL}`)"
      - "traefik.http.services.db.loadbalancer.server.port=80"

  traefik:
    image: traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
volumes:
  my-data:
